import { useState, type FormEvent } from 'react';
import { Link, useLocation, useParams, useSearch } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CircleAlert, CircleHelp, ClipboardList, Plus, Send } from 'lucide-react';
import { getGetPortalSummaryQueryKey, getListServiceRequestsQueryKey, getListInquiriesQueryKey, getGetServiceRequestQueryKey, useGetPortalSummary, useListServiceRequests, useCreateServiceRequest, useGetServiceRequest, useListInquiries, useCreateInquiry, type ServiceRequestInputCategory } from '@workspace/api-client-react';
import { PortalLayout, PageHeading, LoadingBlock, ErrorBlock, EmptyBlock, RequestRow, InquiryRow, Status, StatusTrack, dateText, categoryNames } from '@/components/portal-ui';
import { CustomerAssistant } from '@/components/customer-assistant';

function WaitingOnYou() {
  const q = useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}});
  const waiting = q.data?.filter(r => r.status === 'waiting_on_customer') ?? [];
  if (!waiting.length) return null;
  return <section aria-labelledby="waiting-title" className="mb-8 rounded-2xl border border-[#ecd9a4] bg-[#fbf3dc] p-5 sm:p-6">
    <div className="flex items-start gap-3"><CircleAlert className="mt-0.5 shrink-0 text-[#8a6a14]" size={20}/><div><h2 id="waiting-title" className="font-bold text-[#5f4a10]">{waiting.length === 1 ? 'طلب ينتظر منك إجراءً' : `${new Intl.NumberFormat('ar').format(waiting.length)} طلبات تنتظر منك إجراءً`}</h2><p className="mt-1 text-sm leading-7 text-[#6d5a24]">المكتب بانتظار معلومة أو مستند منك. افتح الطلب واسأل المكتب عمّا يلزم.</p></div></div>
    <div className="mt-4 overflow-hidden rounded-xl bg-[#fffcf3]">{waiting.map(r => <RequestRow key={r.id} request={r}/>)}</div>
  </section>;
}
export function Dashboard() {
  const q = useGetPortalSummary({query:{queryKey:getGetPortalSummaryQueryKey(),refetchInterval:30000}});
  return <PortalLayout><PageHeading eyebrow="نظرة عامة" title="مرحبًا بك في مساحتك" subtitle="كل ما أرسلته للمكتب، مرتب وواضح أمامك." action={<Link href="/requests/new" className="btn btn-primary"><Plus size={18}/>طلب خدمة جديد</Link>}/>
    <WaitingOnYou/>
    {q.isLoading ? <LoadingBlock/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : q.data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['إجمالي الطلبات',q.data.totalRequests],['طلبات قيد المتابعة',q.data.activeRequests],['طلبات مكتملة',q.data.completedRequests],['استفسارات مفتوحة',q.data.openInquiries]].map(([label,value],i) => <div key={label} className={`surface p-5 ${i===0?'!bg-[#174b50] !text-[#f9f3e8]':''}`}><div className={`text-xs font-semibold ${i===0?'text-[#c1d5ce]':'text-[#778a81]'}`}>{label}</div><div className="display mt-5 text-4xl font-semibold" dir="ltr">{value}</div></div>)}</div>
       <div className="mt-10 grid gap-8 xl:grid-cols-[1.3fr_.8fr]"><section><div className="mb-4 flex items-center justify-between"><h2 className="display text-xl font-semibold">أحدث الطلبات</h2><Link href="/requests" className="flex items-center gap-1 text-xs font-bold text-[#b55e3a]">عرض الكل <ArrowLeft size={15}/></Link></div>{q.data.recentRequests.length ? <div className="surface overflow-hidden">{q.data.recentRequests.map(r => <RequestRow key={r.id} request={r}/>)}</div> : <EmptyBlock title="لم ترسل طلبًا بعد" text="ابدأ بإرسال تفاصيل الخدمة التي تحتاجها، وسيتاح لك تتبعها هنا." action="تقديم طلب" href="/requests/new"/>}</section><section><div className="mb-4 flex items-center justify-between"><h2 className="display text-xl font-semibold">أحدث الاستفسارات</h2><Link href="/inquiries" className="flex items-center gap-1 text-xs font-bold text-[#b55e3a]">عرض الكل <ArrowLeft size={15}/></Link></div>{q.data.recentInquiries.length ? <div className="surface overflow-hidden">{q.data.recentInquiries.map(i => <div key={i.id}><InquiryRow inquiry={i}/>{i.linkedServiceRequestReference&&<div className="border-b border-[#e9e5da] px-5 pb-4 text-xs text-[#718079] sm:px-6">مرتبط بالطلب <span dir="ltr" className="font-bold">{i.linkedServiceRequestReference}</span></div>}</div>)}</div> : <EmptyBlock title="لا توجد استفسارات" text="لديك سؤال؟ أرسله إلى المكتب من صفحة الاستفسارات." action="إرسال استفسار" href="/inquiries"/>}</section></div></>}
  </PortalLayout>;
}
export function Requests() {
  const q = useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}}); const [filter,setFilter] = useState('all');
  const filtered = q.data?.filter(r => filter === 'all' || r.status === filter) ?? [];
  return <PortalLayout><PageHeading eyebrow="سجل المعاملات" title="طلباتي" subtitle="جميع الطلبات التي أرسلتها من هذه البوابة." action={<Link href="/requests/new" className="btn btn-primary"><Plus size={18}/>طلب جديد</Link>}/>
    {q.isLoading ? <LoadingBlock/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : !q.data?.length ? <EmptyBlock title="لا توجد طلبات بعد" text="عندما ترسل طلب خدمتك الأول، ستجد تفاصيله وحالته هنا." action="إرسال أول طلب" href="/requests/new"/> : <><div className="mb-5 flex flex-wrap gap-2">{[['all','الكل'],['received','تم الاستلام'],['reviewing','قيد المراجعة'],['waiting_on_customer','بانتظار العميل'],['completed','مكتملة']].map(([key,label]) => <button key={key} onClick={() => setFilter(key)} className={`rounded-full border px-4 py-2 text-xs font-bold transition-colors ${filter===key?'border-[#174b50] bg-[#174b50] text-[#faf5eb]':'border-[#d8ddd3] bg-[#fcfaf4] text-[#61756e] hover:border-[#7d9d93]'}`}>{label}</button>)}</div>{filtered.length ? <div className="surface overflow-hidden">{filtered.map(r => <RequestRow key={r.id} request={r}/>)}</div> : <EmptyBlock title="لا توجد طلبات بهذه الحالة" text="اختر حالة أخرى لعرض الطلبات."/>}</>}
  </PortalLayout>;
}
export function NewRequest() {
  const [,navigate] = useLocation(); const qc = useQueryClient(); const mutation = useCreateServiceRequest();
  const [category,setCategory] = useState<ServiceRequestInputCategory>('passports'); const [service,setService] = useState(''); const [description,setDescription] = useState(''); const [contactPhone,setContactPhone] = useState('');
  async function submit(e:FormEvent) { e.preventDefault(); try { const result = await mutation.mutateAsync({data:{category,service:service.trim(),description:description.trim(),contactPhone:contactPhone.trim()}}); await Promise.all([qc.invalidateQueries({queryKey:getListServiceRequestsQueryKey()}),qc.invalidateQueries({queryKey:getGetPortalSummaryQueryKey()})]); navigate(`/requests/${result.id}`); } catch { /* mutation error displayed */ } }
  return <PortalLayout><div className="max-w-[740px]"><Link href="/requests" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-[#697f76]"><ArrowRight size={16}/>العودة إلى الطلبات</Link><PageHeading eyebrow="طلب خدمة" title="أخبرنا بما تحتاجه" subtitle="اختر مجال الخدمة، واكتب اسم الخدمة وتفاصيلها ورقمًا للتواصل. بعد الإرسال، ستجد الطلب ورقمه المرجعي في حسابك."/>
    <form onSubmit={submit} className="surface space-y-6 p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="form-field">مجال الخدمة<select className="form-control" value={category} onChange={e=>setCategory(e.target.value as ServiceRequestInputCategory)} required><option value="passports">الجوازات</option><option value="labor">العمل</option><option value="business">الأعمال</option><option value="other">خدمات أخرى</option></select></label><label className="form-field">اسم الخدمة المطلوبة<input className="form-control" placeholder="مثل: متابعة طلب جواز" value={service} onChange={e=>setService(e.target.value)} minLength={2} maxLength={120} required/></label></div><label className="form-field">تفاصيل الطلب<textarea className="form-control" placeholder="اكتب ما تريد من المكتب معرفته عن معاملتك..." value={description} onChange={e=>setDescription(e.target.value)} minLength={10} maxLength={5000} required/><small className="muted font-normal">يرجى كتابة التفاصيل الضرورية دون مشاركة كلمات مرور أو معلومات حساسة غير مطلوبة.</small></label><label className="form-field">رقم للتواصل<input dir="ltr" className="form-control text-right" type="tel" placeholder="رقم هاتفك" value={contactPhone} onChange={e=>setContactPhone(e.target.value)} minLength={9} maxLength={24} required/></label>{mutation.isError && <div role="alert" className="rounded-lg bg-[#f9e6df] p-4 text-sm text-[#a83f2e]">تعذّر إرسال الطلب. راجع البيانات وحاول مرة أخرى.</div>}<div className="flex flex-col-reverse items-start justify-between gap-4 border-t border-[#e4e2d8] pt-6 sm:flex-row sm:items-center"><p className="muted max-w-xs text-xs leading-6">بعد إرسال الطلب، يظهر رقمه المرجعي وحالته في سجل طلباتك.</p><button className="btn btn-primary w-full sm:w-auto" disabled={mutation.isPending} type="submit">{mutation.isPending?'جارٍ إرسال الطلب...':'إرسال الطلب'}<Send size={16}/></button></div></form></div>
  </PortalLayout>;
}
export function RequestDetail() {
  const {id} = useParams<{id:string}>(); const parsed = Number(id); const q = useGetServiceRequest(parsed,{query:{enabled:Number.isInteger(parsed)&&parsed>0,queryKey:getGetServiceRequestQueryKey(parsed),refetchInterval:30000}});
  return <PortalLayout><div className="max-w-[860px]"><Link href="/requests" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-[#697f76]"><ArrowRight size={16}/>العودة إلى الطلبات</Link>{!Number.isInteger(parsed)||parsed<=0 ? <EmptyBlock title="الطلب غير متاح" text="تحقق من رابط الطلب وحاول مرة أخرى."/> : q.isLoading ? <LoadingBlock/> : q.error?.status === 404 ? <EmptyBlock title="الطلب غير متاح" text="هذا الطلب غير موجود في حسابك."/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : q.data && <><PageHeading eyebrow={`طلب رقم ${q.data.reference}`} title={q.data.service} subtitle={`أُرسل في ${dateText(q.data.createdAt)}`}/><div className="surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#e5e5db] bg-[#eaf0e9] p-6"><div><div className="text-xs font-semibold text-[#718279]">الحالة الحالية</div><div className="mt-2"><Status value={q.data.status}/></div></div><ClipboardList className="text-[#6d938c]" size={30}/></div><div className="border-b border-[#e5e5db] px-6 py-5 sm:px-8"><StatusTrack status={q.data.status}/>{q.data.status==='waiting_on_customer'&&<p className="mt-4 flex items-start gap-2 rounded-lg bg-[#fbf3dc] p-3 text-sm leading-7 text-[#6d5a24]"><CircleAlert className="mt-1 shrink-0" size={16}/>المكتب بانتظار معلومة أو مستند منك لإكمال الطلب. اسأل المكتب عمّا يلزم.</p>}</div><div className="grid gap-7 p-6 sm:grid-cols-2 sm:p-8"><Info label="الرقم المرجعي" value={q.data.reference} ltr/><Info label="مجال الخدمة" value={categoryNames[q.data.category]}/><Info label="رقم التواصل" value={q.data.contactPhone} ltr/><Info label="آخر تحديث" value={dateText(q.data.updatedAt)}/><div className="sm:col-span-2"><div className="mb-2 text-xs font-bold text-[#819088]">التفاصيل التي أرسلتها</div><p className="whitespace-pre-wrap text-sm leading-8">{q.data.description}</p></div></div></div><p className="muted mt-5 text-xs leading-6">لديك سؤال عن هذا الطلب؟ أرسله للمكتب وسيكون مرتبطًا بالطلب.</p><Link href={`/inquiries?request=${q.data.id}`} className="btn btn-outline mt-4"><CircleHelp size={17}/>استفسر عن هذا الطلب</Link></>}</div></PortalLayout>;
}
function Info({label,value,ltr=false}:{label:string;value:string;ltr?:boolean}) { return <div><div className="mb-2 text-xs font-bold text-[#819088]">{label}</div><div className="font-semibold" dir={ltr?'ltr':undefined} style={ltr?{textAlign:'right'}:undefined}>{value}</div></div>; }
export function Inquiries() {
  const requestFromLink = Number(new URLSearchParams(useSearch()).get('request')) || null;
  const q=useListInquiries({query:{queryKey:getListInquiriesQueryKey(),refetchInterval:30000}}); const requests=useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}}); const qc=useQueryClient(); const mutation=useCreateInquiry(); const [subject,setSubject]=useState(''); const [message,setMessage]=useState(''); const [linkedServiceRequestId,setLinkedServiceRequestId]=useState(requestFromLink ? String(requestFromLink) : ''); const [showForm,setShowForm]=useState(Boolean(requestFromLink));
  async function submit(e:FormEvent) { e.preventDefault(); try { await mutation.mutateAsync({data:{subject:subject.trim(),message:message.trim(),linkedServiceRequestId:linkedServiceRequestId?Number(linkedServiceRequestId):null}}); setSubject('');setMessage('');setLinkedServiceRequestId('');setShowForm(false); await Promise.all([qc.invalidateQueries({queryKey:getListInquiriesQueryKey()}),qc.invalidateQueries({queryKey:getGetPortalSummaryQueryKey()})]); } catch { /* error shown */ } }
  return <PortalLayout><PageHeading eyebrow="تواصل مع المكتب" title="استفساراتي" subtitle="أرسل استفسارًا إلى المكتب؛ وعند إضافة المكتب ردًا، ستجده في سجل استفساراتك." action={<button onClick={()=>setShowForm(v=>!v)} className="btn btn-primary"><Plus size={18}/>{showForm?'إغلاق النموذج':'استفسار جديد'}</button>}/>
    {showForm && <form onSubmit={submit} className="surface mb-8 max-w-[760px] space-y-5 p-5 sm:p-8"><h2 className="display text-xl font-semibold">استفسار جديد</h2><label className="form-field">عنوان الاستفسار<input className="form-control" placeholder="ما موضوع سؤالك؟" value={subject} onChange={e=>setSubject(e.target.value)} minLength={3} maxLength={160} required/></label><label className="form-field">رسالتك<textarea className="form-control" placeholder="اكتب سؤالك بالتفصيل..." value={message} onChange={e=>setMessage(e.target.value)} minLength={10} maxLength={5000} required/></label><label className="form-field">ربط الاستفسار بطلب خدمة (اختياري)<select className="form-control" value={linkedServiceRequestId} onChange={e=>setLinkedServiceRequestId(e.target.value)}><option value="">بدون ربط</option>{requests.data?.map(r=><option key={r.id} value={r.id}>{r.reference} · {r.service}</option>)}</select><small className="muted font-normal">يمكنك اختيار طلب واحد من طلباتك فقط. سيطّلع المكتب على تفاصيل الطلب المرتبط لمساعدتك.</small></label>{requests.isError&&<p role="alert" className="text-sm text-[#b43f35]">تعذّر تحميل طلباتك. أعد المحاولة قبل اختيار طلب للربط.</p>}{mutation.isError && <p role="alert" className="text-sm text-[#b43f35]">تعذّر إرسال الاستفسار. حاول مجددًا.</p>}<button disabled={mutation.isPending} type="submit" className="btn btn-primary">{mutation.isPending?'جارٍ الإرسال...':'إرسال الاستفسار'}<Send size={16}/></button></form>}
    <CustomerAssistant onAskOffice={() => setShowForm(true)}/>
    <h2 className="display mb-4 text-xl font-semibold">سجل الاستفسارات</h2>{q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<EmptyBlock title="لا توجد استفسارات بعد" text="أرسل سؤالك للمكتب وستجد ردّه هنا بعد الإجابة عليه." action="اكتب استفسارك" href={undefined}/>:<div className="surface overflow-hidden">{q.data.map(i=><div key={i.id}><InquiryRow inquiry={i}/>{i.linkedServiceRequestReference&&<div className="border-b border-[#e9e5da] px-5 pb-4 text-xs text-[#718079] sm:px-6">مرتبط بالطلب <span dir="ltr" className="font-bold">{i.linkedServiceRequestReference}</span></div>}</div>)}</div>}
  </PortalLayout>;
}