import { useState, type FormEvent } from 'react';
import { Link, useParams, useSearch } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CircleAlert, CircleCheck, CircleHelp, ClipboardList, Plus, Send } from 'lucide-react';
import { getGetPortalSummaryQueryKey, getListServiceRequestsQueryKey, getListInquiriesQueryKey, getGetServiceRequestQueryKey, useGetPortalSummary, useListServiceRequests, useGetServiceRequest, useListInquiries, useCreateInquiry } from '@workspace/api-client-react';
import { PortalLayout, PageHeading, LoadingBlock, ErrorBlock, EmptyBlock, RequestRow, InquiryRow, Status, StatusTrack, dateText, categoryNames } from '@/components/portal-ui';
import { CustomerAssistant } from '@/components/customer-assistant';
import { LOCALE } from '@/lib/format';

function WaitingOnYou() {
  const q = useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}});
  const waiting = q.data?.filter(r => r.status === 'waiting_on_customer') ?? [];
  if (!waiting.length) return null;
  return <section aria-labelledby="waiting-title" className="mb-8 rounded-2xl border border-warn-line bg-warn-soft p-5 sm:p-6">
    <div className="flex items-start gap-3"><CircleAlert className="mt-0.5 shrink-0 text-warn" size={20}/><div><h2 id="waiting-title" className="font-bold text-warn">{waiting.length === 1 ? 'طلب ينتظر منك إجراءً' : `${new Intl.NumberFormat(LOCALE).format(waiting.length)} طلبات تنتظر منك إجراءً`}</h2><p className="mt-1 text-sm leading-7 text-warn">المكتب بانتظار معلومة أو مستند منك. افتح الطلب واسأل المكتب عمّا يلزم.</p></div></div>
    <div className="mt-4 overflow-hidden rounded-xl bg-field">{waiting.map(r => <RequestRow key={r.id} request={r}/>)}</div>
  </section>;
}
export function Dashboard() {
  const q = useGetPortalSummary({query:{queryKey:getGetPortalSummaryQueryKey(),refetchInterval:30000}});
  return <PortalLayout><PageHeading eyebrow="نظرة عامة" title="مرحبًا بك في مساحتك" subtitle="كل ما أرسلته للمكتب، مرتب وواضح أمامك." action={<Link href="/requests/new" className="btn btn-primary"><Plus size={18}/>طلب خدمة جديد</Link>}/>
    <WaitingOnYou/>
    {q.isLoading ? <LoadingBlock/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : q.data && <><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['إجمالي الطلبات',q.data.totalRequests],['طلبات قيد المتابعة',q.data.activeRequests],['طلبات مكتملة',q.data.completedRequests],['استفسارات مفتوحة',q.data.openInquiries]].map(([label,value],i) => <div key={label} className={`surface p-4 sm:p-5 ${i===1?'!bg-teal !text-on-dark':''}`}><div className={`text-xs font-semibold ${i===1?'text-on-dark-2':'text-subtle'}`}>{label}</div><div className="display mt-3 text-3xl font-semibold sm:mt-5 sm:text-4xl" dir="ltr">{value}</div></div>)}</div>
       <div className="mt-10 grid gap-8 xl:grid-cols-[1.3fr_.8fr]"><section><div className="mb-4 flex items-center justify-between"><h2 className="display text-xl font-semibold">أحدث الطلبات</h2><Link href="/requests" className="flex items-center gap-1 text-xs font-bold text-copper">عرض الكل <ArrowLeft size={15}/></Link></div>{q.data.recentRequests.length ? <div className="surface overflow-hidden">{q.data.recentRequests.map(r => <RequestRow key={r.id} request={r}/>)}</div> : <EmptyBlock title="لم ترسل طلبًا بعد" text="ابدأ بإرسال تفاصيل الخدمة التي تحتاجها، وسيتاح لك تتبعها هنا." action="تقديم طلب" href="/requests/new"/>}</section><section><div className="mb-4 flex items-center justify-between"><h2 className="display text-xl font-semibold">أحدث الاستفسارات</h2><Link href="/inquiries" className="flex items-center gap-1 text-xs font-bold text-copper">عرض الكل <ArrowLeft size={15}/></Link></div>{q.data.recentInquiries.length ? <div className="surface overflow-hidden">{q.data.recentInquiries.map(i => <div key={i.id}><InquiryRow inquiry={i}/>{i.linkedServiceRequestReference&&<div className="border-b border-line px-5 pb-4 text-xs text-subtle sm:px-6">مرتبط بالطلب <span dir="ltr" className="font-bold">{i.linkedServiceRequestReference}</span></div>}</div>)}</div> : <EmptyBlock title="لا توجد استفسارات" text="لديك سؤال؟ أرسله إلى المكتب من صفحة الاستفسارات." action="إرسال استفسار" href="/inquiries"/>}</section></div></>}
  </PortalLayout>;
}
export function Requests() {
  const q = useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}}); const [filter,setFilter] = useState('all');
  const filtered = q.data?.filter(r => filter === 'all' || r.status === filter) ?? [];
  return <PortalLayout><PageHeading eyebrow="سجل المعاملات" title="طلباتي" subtitle="جميع الطلبات التي أرسلتها من هذه البوابة." action={<Link href="/requests/new" className="btn btn-primary"><Plus size={18}/>طلب جديد</Link>}/>
    {q.isLoading ? <LoadingBlock/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : !q.data?.length ? <EmptyBlock title="لا توجد طلبات بعد" text="عندما ترسل طلب خدمتك الأول، ستجد تفاصيله وحالته هنا." action="إرسال أول طلب" href="/requests/new"/> : <><div className="mb-5 flex flex-wrap gap-2">{[['all','الكل'],['received','تم الاستلام'],['reviewing','قيد المراجعة'],['waiting_on_customer','بانتظار العميل'],['completed','مكتملة']].map(([key,label]) => <button key={key} onClick={() => setFilter(key)} className={`rounded-full border px-4 py-2 text-xs font-bold transition-colors ${filter===key?'border-teal bg-teal text-on-dark':'border-sage-2 bg-surface text-subtle hover:border-line-dark-2'}`}>{label}</button>)}</div>{filtered.length ? <div className="surface overflow-hidden">{filtered.map(r => <RequestRow key={r.id} request={r}/>)}</div> : <EmptyBlock title="لا توجد طلبات بهذه الحالة" text="اختر حالة أخرى لعرض الطلبات."/>}</>}
  </PortalLayout>;
}
export { NewRequest } from './new-request';
export function RequestDetail() {
  const {id} = useParams<{id:string}>(); const parsed = Number(id); const justSent = new URLSearchParams(useSearch()).get('sent') === '1'; const q = useGetServiceRequest(parsed,{query:{enabled:Number.isInteger(parsed)&&parsed>0,queryKey:getGetServiceRequestQueryKey(parsed),refetchInterval:30000}});
  return <PortalLayout><div className="max-w-[860px]"><Link href="/requests" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-subtle"><ArrowRight size={16}/>العودة إلى الطلبات</Link>{!Number.isInteger(parsed)||parsed<=0 ? <EmptyBlock title="الطلب غير متاح" text="تحقق من رابط الطلب وحاول مرة أخرى."/> : q.isLoading ? <LoadingBlock/> : q.error?.status === 404 ? <EmptyBlock title="الطلب غير متاح" text="هذا الطلب غير موجود في حسابك."/> : q.isError ? <ErrorBlock retry={() => q.refetch()}/> : q.data && <>{justSent && <div role="status" className="rise mb-6 flex items-start gap-3 rounded-2xl border border-sage-2 bg-ok-soft p-5 text-ok"><CircleCheck className="mt-0.5 shrink-0" size={22}/><div><strong className="block text-ink">وصل طلبك إلى المكتب.</strong><span className="text-sm">رقمك المرجعي <span dir="ltr" className="nums font-bold">{q.data.reference}</span>. ستجد كل تحديث على هذه الصفحة.</span></div></div>}<PageHeading eyebrow={`طلب رقم ${q.data.reference}`} title={q.data.service} subtitle={`أُرسل في ${dateText(q.data.createdAt)}`}/><div className="surface overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-line bg-sage p-6"><div><div className="text-xs font-semibold text-subtle">الحالة الحالية</div><div className="mt-2"><Status value={q.data.status}/></div></div><ClipboardList className="text-subtle" size={30}/></div><div className="border-b border-line px-6 py-5 sm:px-8"><StatusTrack status={q.data.status} createdAt={q.data.createdAt} updatedAt={q.data.updatedAt}/>{q.data.status==='waiting_on_customer'&&<p className="mt-4 flex items-start gap-2 rounded-lg bg-warn-soft p-3 text-sm leading-7 text-warn"><CircleAlert className="mt-1 shrink-0" size={16}/>المكتب بانتظار معلومة أو مستند منك لإكمال الطلب. اسأل المكتب عمّا يلزم.</p>}</div><div className="grid gap-7 p-6 sm:grid-cols-2 sm:p-8"><Info label="الرقم المرجعي" value={q.data.reference} ltr/><Info label="مجال الخدمة" value={categoryNames[q.data.category]}/><Info label="رقم التواصل" value={q.data.contactPhone} ltr/><Info label="آخر تحديث" value={dateText(q.data.updatedAt)}/><div className="sm:col-span-2"><div className="mb-2 text-xs font-bold text-subtle">التفاصيل التي أرسلتها</div><p className="whitespace-pre-wrap text-sm leading-8">{q.data.description}</p></div></div></div><p className="muted mt-5 text-xs leading-6">لديك سؤال عن هذا الطلب؟ أرسله للمكتب وسيكون مرتبطًا بالطلب.</p><Link href={`/inquiries?request=${q.data.id}`} className="btn btn-outline mt-4"><CircleHelp size={17}/>استفسر عن هذا الطلب</Link></>}</div></PortalLayout>;
}
function Info({label,value,ltr=false}:{label:string;value:string;ltr?:boolean}) { return <div><div className="mb-2 text-xs font-bold text-subtle">{label}</div><div className="font-semibold" dir={ltr?'ltr':undefined} style={ltr?{textAlign:'right'}:undefined}>{value}</div></div>; }
export function Inquiries() {
  const requestFromLink = Number(new URLSearchParams(useSearch()).get('request')) || null;
  const q=useListInquiries({query:{queryKey:getListInquiriesQueryKey(),refetchInterval:30000}}); const requests=useListServiceRequests({query:{queryKey:getListServiceRequestsQueryKey(),refetchInterval:30000}}); const qc=useQueryClient(); const mutation=useCreateInquiry(); const [subject,setSubject]=useState(''); const [message,setMessage]=useState(''); const [linkedServiceRequestId,setLinkedServiceRequestId]=useState(requestFromLink ? String(requestFromLink) : ''); const [showForm,setShowForm]=useState(Boolean(requestFromLink));
  async function submit(e:FormEvent) { e.preventDefault(); try { await mutation.mutateAsync({data:{subject:subject.trim(),message:message.trim(),linkedServiceRequestId:linkedServiceRequestId?Number(linkedServiceRequestId):null}}); setSubject('');setMessage('');setLinkedServiceRequestId('');setShowForm(false); await Promise.all([qc.invalidateQueries({queryKey:getListInquiriesQueryKey()}),qc.invalidateQueries({queryKey:getGetPortalSummaryQueryKey()})]); } catch { /* error shown */ } }
  return <PortalLayout><PageHeading eyebrow="تواصل مع المكتب" title="استفساراتي" subtitle="أرسل استفسارًا إلى المكتب؛ وعند إضافة المكتب ردًا، ستجده في سجل استفساراتك." action={<button onClick={()=>setShowForm(v=>!v)} className="btn btn-primary"><Plus size={18}/>{showForm?'إغلاق النموذج':'استفسار جديد'}</button>}/>
    {showForm && <form onSubmit={submit} className="surface mb-8 max-w-[760px] space-y-5 p-5 sm:p-8"><h2 className="display text-xl font-semibold">استفسار جديد</h2><label className="form-field">عنوان الاستفسار<input className="form-control" placeholder="ما موضوع سؤالك؟" value={subject} onChange={e=>setSubject(e.target.value)} minLength={3} maxLength={160} required/></label><label className="form-field">رسالتك<textarea className="form-control" placeholder="اكتب سؤالك بالتفصيل..." value={message} onChange={e=>setMessage(e.target.value)} minLength={10} maxLength={5000} required/></label><label className="form-field">ربط الاستفسار بطلب خدمة (اختياري)<select className="form-control" value={linkedServiceRequestId} onChange={e=>setLinkedServiceRequestId(e.target.value)}><option value="">بدون ربط</option>{requests.data?.map(r=><option key={r.id} value={r.id}>{r.reference} · {r.service}</option>)}</select><small className="muted font-normal">يمكنك اختيار طلب واحد من طلباتك فقط. سيطّلع المكتب على تفاصيل الطلب المرتبط لمساعدتك.</small></label>{requests.isError&&<p role="alert" className="text-sm text-danger">تعذّر تحميل طلباتك. أعد المحاولة قبل اختيار طلب للربط.</p>}{mutation.isError && <p role="alert" className="text-sm text-danger">تعذّر إرسال الاستفسار. حاول مجددًا.</p>}<button disabled={mutation.isPending} type="submit" className="btn btn-primary">{mutation.isPending?'جارٍ الإرسال...':'إرسال الاستفسار'}<Send size={16}/></button></form>}
    <CustomerAssistant onAskOffice={() => setShowForm(true)}/>
    <h2 className="display mb-4 text-xl font-semibold">سجل الاستفسارات</h2>{q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<EmptyBlock title="لا توجد استفسارات بعد" text="أرسل سؤالك للمكتب وستجد ردّه هنا بعد الإجابة عليه." action="اكتب استفسارك" onAction={()=>setShowForm(true)}/>:<div className="surface overflow-hidden">{q.data.map(i=><div key={i.id}><InquiryRow inquiry={i}/>{i.linkedServiceRequestReference&&<div className="border-b border-line px-5 pb-4 text-xs text-subtle sm:px-6">مرتبط بالطلب <span dir="ltr" className="font-bold">{i.linkedServiceRequestReference}</span></div>}</div>)}</div>}
  </PortalLayout>;
}