import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearch } from 'wouter';
import { keepPreviousData, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ClipboardList, Clock3, Mail, MessageSquareText, Save, Search, Send, UserRound } from 'lucide-react';
import { getGetOfficeSummaryQueryKey, getListOfficeServiceRequestsQueryKey, getListOfficeInquiriesQueryKey, useGetOfficeSummary, useListOfficeServiceRequests, useUpdateOfficeServiceRequest, useListOfficeInquiries, useAnswerOfficeInquiry, type ListOfficeInquiriesStatus, type ListOfficeServiceRequestsCategory, type ListOfficeServiceRequestsSort, type ListOfficeServiceRequestsStatus, type OfficeCustomer, type OfficeServiceRequest, type OfficeInquiry, type ServiceRequestUpdateStatus } from '@workspace/api-client-react';
import { PortalLayout, PageHeading, LoadingBlock, ErrorBlock, EmptyBlock, Pager, STALE_AFTER_DAYS, StaleBadge, Status, dateText, categoryNames, isStale, statusOptions, statusNames, useDebouncedValue } from '@/components/portal-ui';
import { LOCALE } from '@/lib/format';
import { RequestFiles } from '@/components/request-files';

export function OfficeOverview() {
  const q=useGetOfficeSummary({query:{queryKey:getGetOfficeSummaryQueryKey(),refetchInterval:30000}});
  const count=(value:number)=>new Intl.NumberFormat(LOCALE).format(value);
  return <PortalLayout staff><PageHeading eyebrow="" title="نظرة عامة"/>
    {q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:q.data&&<div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{([
        ['طلبات جديدة',q.data.newRequests,'/office/requests?status=received'],
        ['طلبات نشطة',q.data.activeRequests,null],
        ['استفسارات مفتوحة',q.data.openInquiries,'/office/inquiries'],
        ['إجمالي الطلبات',q.data.totalRequests,'/office/requests'],
      ] as const).map(([label,value,href],i)=>{
        const body=<><div className={`flex items-center justify-between gap-2 text-xs font-bold ${i===0?'text-on-dark-2':'text-subtle'}`}>{label}{href&&<ArrowLeft size={15} className="shrink-0 transition-transform group-hover:-translate-x-1"/>}</div><div className="display nums mt-3 text-3xl font-semibold sm:mt-4 sm:text-4xl">{count(value)}</div></>;
        const cls=`surface block p-4 text-inherit no-underline sm:p-5 ${i===0?'!bg-teal !text-on-dark':''}`;
        return href?<Link key={label} href={href} className={`group ${cls} transition-colors hover:border-line-strong`}>{body}</Link>:<div key={label} className={cls}>{body}</div>;
      })}</div>
      {q.data.staleRequests>0&&<Link href="/office/requests?sort=oldest_update" className="flex min-h-11 flex-wrap items-center justify-between gap-3 rounded-xl border border-warn-line bg-warn-soft px-5 py-4 text-sm text-warn no-underline"><span className="flex items-center gap-2"><Clock3 size={17} className="shrink-0"/><span><strong className="nums">{count(q.data.staleRequests)}</strong> {q.data.staleRequests===1?'طلب نشط':'طلبات نشطة'} بلا تحديث منذ {count(STALE_AFTER_DAYS)} أيام أو أكثر</span></span><span className="flex items-center gap-1 font-bold">عرض من الأقدم تحديثًا<ArrowLeft size={15}/></span></Link>}
    </div>}
  </PortalLayout>;
}
// Below the xl breakpoint the editor sits under the list, so bring it into view.
function useRevealOnSelect(selected: number | null) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (selected != null && !window.matchMedia('(min-width: 1280px)').matches) ref.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [selected]);
  return ref;
}
function CustomerLine({customer}:{customer:OfficeCustomer|null}) {
  return customer ? <span className="font-semibold text-quiet">{customer.fullName}</span> : <span className="text-subtle">بلا طلب تسجيل</span>;
}
function CustomerCard({customer}:{customer:OfficeCustomer|null}) {
  if (!customer) return <div className="rounded-lg bg-sunk p-3 text-xs text-subtle">لا يوجد طلب تسجيل لهذا العميل.</div>;
  return <div className="flex items-start gap-3 rounded-lg bg-sunk p-3"><UserRound className="mt-0.5 shrink-0 text-subtle" size={18}/><div className="min-w-0 text-xs"><div className="font-bold text-ink">{customer.fullName}</div><a href={`mailto:${customer.email}`} dir="ltr" className="mt-1 inline-flex items-center gap-1 break-all text-teal-bright"><Mail size={13}/>{customer.email}</a></div></div>;
}
function ResultCount({total}:{total:number}) {
  return <p className="mb-2 text-xs font-semibold text-subtle" aria-live="polite">عدد النتائج: <span className="nums">{new Intl.NumberFormat(LOCALE).format(total)}</span></p>;
}
const requestSorts: Record<ListOfficeServiceRequestsSort,string> = { newest: 'الأحدث إرسالًا', oldest_update: 'الأقدم تحديثًا' };
export function OfficeRequests() {
  const initial=new URLSearchParams(useSearch());
  const [search,setSearch]=useState(''); const q=useDebouncedValue(search.trim());
  const [status,setStatus]=useState<ListOfficeServiceRequestsStatus|''>(() => (statusOptions as string[]).includes(initial.get('status')??'') ? initial.get('status') as ListOfficeServiceRequestsStatus : '');
  const [category,setCategory]=useState<ListOfficeServiceRequestsCategory|''>('');
  const [sort,setSort]=useState<ListOfficeServiceRequestsSort>(initial.get('sort')==='oldest_update'?'oldest_update':'newest');
  const [page,setPage]=useState(1); const [selected,setSelected]=useState<number|null>(null);
  useEffect(()=>setPage(1),[q,status,category,sort]);
  const params={...(status?{status}:{}),...(category?{category}:{}),...(q?{q}:{}),sort,page};
  const list=useListOfficeServiceRequests(params,{query:{queryKey:getListOfficeServiceRequestsQueryKey(params),placeholderData:keepPreviousData,refetchInterval:30000}});
  const rows=list.data?.items??[]; const active=rows.find(r=>r.id===selected);
  const filtered=Boolean(q||status||category);
  const editorRef=useRevealOnSelect(selected);
  return <PortalLayout staff><PageHeading eyebrow="" title="طلبات العملاء"/>
    <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-[minmax(0,1fr)_repeat(3,11rem)]">
      <label className="relative col-span-2 lg:col-span-1"><span className="sr-only">بحث في الطلبات</span><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-subtle" size={17}/><input className="form-control !pr-10" placeholder="ابحث بالاسم أو البريد أو الرقم المرجعي أو الخدمة" value={search} onChange={e=>setSearch(e.target.value)} maxLength={120}/></label>
      <label><span className="sr-only">الحالة</span><select className="form-control" value={status} onChange={e=>setStatus(e.target.value as ListOfficeServiceRequestsStatus|'')}><option value="">كل الحالات</option>{statusOptions.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select></label>
      <label><span className="sr-only">المجال</span><select className="form-control" value={category} onChange={e=>setCategory(e.target.value as ListOfficeServiceRequestsCategory|'')}><option value="">كل المجالات</option>{Object.entries(categoryNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <label className="col-span-2 lg:col-span-1"><span className="sr-only">الترتيب</span><select className="form-control" value={sort} onChange={e=>setSort(e.target.value as ListOfficeServiceRequestsSort)}>{Object.entries(requestSorts).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
    </div>
    {list.isLoading?<LoadingBlock/>:list.isError?<ErrorBlock retry={()=>list.refetch()}/>:!list.data?.total&&!filtered?<EmptyBlock title="لا توجد طلبات واردة" text="ستظهر طلبات العملاء هنا عند إرسالها عبر البوابة."/>:<div className="grid grid-cols-1 items-start gap-5 xl:grid-cols-[minmax(0,1fr)_400px]"><div className="min-w-0"><ResultCount total={list.data?.total??0}/><div className={`surface overflow-hidden transition-opacity ${list.isPlaceholderData?'opacity-60':''}`}>{rows.length?rows.map(r=><button key={r.id} type="button" aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)} className={`block w-full border-b border-line px-5 py-4 text-right transition-colors last:border-0 hover:bg-paper sm:px-6 ${selected===r.id?'!bg-sage shadow-[inset_-3px_0_0_var(--color-teal)]':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-bold">{r.service}</div><div className="mt-1 text-xs"><CustomerLine customer={r.customer}/></div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-subtle"><span dir="ltr" className="nums">{r.reference}</span><span>{categoryNames[r.category]}</span><span>{dateText(r.createdAt)}</span>{isStale(r)&&<StaleBadge updatedAt={r.updatedAt}/>}</div></div><Status value={r.status}/></div></button>):<div className="p-10 text-center text-sm text-subtle">لا توجد طلبات مطابقة للبحث أو التصفية.</div>}</div>{list.data&&<Pager page={list.data.page} pageSize={list.data.pageSize} total={list.data.total} onPage={setPage}/>}</div><div ref={editorRef} className="scroll-mt-24 xl:sticky xl:top-24">{active?<RequestEditor key={active.id} request={active}/>:<div className="surface hidden min-h-64 flex-col items-center justify-center p-8 text-center text-subtle xl:flex"><ClipboardList className="mb-3" size={30} strokeWidth={1.5}/><p className="text-sm">اختر طلبًا لعرض تفاصيله وتحديث حالته.</p></div>}</div></div>}
  </PortalLayout>;
}
function RequestEditor({request}:{request:OfficeServiceRequest}) {
  const qc=useQueryClient(); const mutation=useUpdateOfficeServiceRequest(); const [status,setStatus]=useState<ServiceRequestUpdateStatus>(request.status); const [officeNote,setOfficeNote]=useState(request.officeNote??''); const [saved,setSaved]=useState(false);
  useEffect(()=>{setStatus(request.status);setOfficeNote(request.officeNote??'');setSaved(false)},[request.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:request.id,data:{status,officeNote:officeNote.trim()||null}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeServiceRequestsQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-line bg-sage p-5"><div className="flex items-start justify-between gap-3"><div><span className="nums text-xs font-bold text-subtle" dir="ltr">{request.reference}</span><h2 className="display mt-1 text-lg font-semibold leading-8">{request.service}</h2></div><Status value={request.status}/></div></div><div className="space-y-5 p-5"><CustomerCard customer={request.customer}/>{isStale(request)&&<StaleBadge updatedAt={request.updatedAt}/>}<dl className="m-0 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><div><dt className="text-xs text-subtle">المجال</dt><dd className="m-0 mt-0.5 font-semibold">{categoryNames[request.category]}</dd></div><div><dt className="text-xs text-subtle">تاريخ الإرسال</dt><dd className="m-0 mt-0.5 font-semibold">{dateText(request.createdAt)}</dd></div><div className="col-span-2"><dt className="text-xs text-subtle">رقم التواصل</dt><dd className="m-0 mt-0.5 font-semibold"><span dir="ltr" className="nums inline-block">{request.contactPhone}</span></dd></div></dl><div className="border-t border-line pt-4"><div className="mb-2 text-xs font-bold text-subtle">تفاصيل الطلب</div><p className="max-h-44 overflow-y-auto whitespace-pre-wrap text-sm leading-7">{request.description}</p></div><div className="border-t border-line pt-4"><RequestFiles key={request.id} scope="office" requestId={request.id} canUpload/></div><form onSubmit={submit} className="space-y-4 border-t border-line pt-5"><label className="form-field">الحالة<select className="form-control" value={status} onChange={e=>setStatus(e.target.value as ServiceRequestUpdateStatus)}>{statusOptions.map(s=><option value={s} key={s}>{statusNames[s]}</option>)}</select></label><label className="form-field">ملاحظة داخلية<textarea className="form-control !min-h-28" value={officeNote} onChange={e=>setOfficeNote(e.target.value)} maxLength={2000} placeholder="ملاحظة لفريق المكتب"/><small className="muted font-normal">لا تظهر للعميل.</small></label>{mutation.isError&&<p role="alert" className="text-xs text-danger">تعذّر حفظ التحديث. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-ok">تم حفظ التحديث.</p>}<button type="submit" disabled={mutation.isPending} className="btn btn-primary w-full">{mutation.isPending?'جارٍ الحفظ…':'حفظ التحديث'}<Save size={16}/></button></form></div></div>;
}
const inquiryFilters: [ListOfficeInquiriesStatus|'', string][] = [['open','المفتوحة'],['answered','المجاب عنها'],['','الكل']];
export function OfficeInquiries(){
  const [search,setSearch]=useState(''); const q=useDebouncedValue(search.trim());
  const [status,setStatus]=useState<ListOfficeInquiriesStatus|''>('open'); const [page,setPage]=useState(1); const [selected,setSelected]=useState<number|null>(null);
  useEffect(()=>setPage(1),[q,status]);
  const params={...(status?{status}:{}),...(q?{q}:{}),page};
  const list=useListOfficeInquiries(params,{query:{queryKey:getListOfficeInquiriesQueryKey(params),placeholderData:keepPreviousData,refetchInterval:30000}});
  const rows=list.data?.items??[]; const active=rows.find(i=>i.id===selected);
  const editorRef=useRevealOnSelect(selected);
  return <PortalLayout staff><PageHeading eyebrow="" title="استفسارات العملاء"/>
    <div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex gap-2" role="group" aria-label="تصفية حسب الحالة">{inquiryFilters.map(([key,label])=><button key={label} type="button" onClick={()=>setStatus(key)} aria-pressed={status===key} className={`min-h-11 flex-1 rounded-full border px-4 text-xs font-bold transition-colors lg:flex-none ${status===key?'border-teal bg-teal text-on-dark':'border-line-strong bg-surface text-quiet hover:bg-sage'}`}>{label}</button>)}</div><label className="relative flex-1"><span className="sr-only">بحث في الاستفسارات</span><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-subtle" size={17}/><input className="form-control !pr-10" placeholder="ابحث بالاسم أو البريد أو الموضوع" value={search} onChange={e=>setSearch(e.target.value)} maxLength={120}/></label></div>
    {list.isLoading?<LoadingBlock/>:list.isError?<ErrorBlock retry={()=>list.refetch()}/>:<div className="grid grid-cols-1 items-start gap-5 xl:grid-cols-[minmax(0,1fr)_400px]"><div className="min-w-0"><ResultCount total={list.data?.total??0}/><div className={`surface overflow-hidden transition-opacity ${list.isPlaceholderData?'opacity-60':''}`}>{rows.length?rows.map(i=><button key={i.id} type="button" aria-pressed={selected===i.id} onClick={()=>setSelected(i.id)} className={`block w-full border-b border-line px-5 py-4 text-right transition-colors last:border-0 hover:bg-paper sm:px-6 ${selected===i.id?'!bg-sage shadow-[inset_-3px_0_0_var(--color-teal)]':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-bold">{i.subject}</div><div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs"><CustomerLine customer={i.customer}/><span className="text-subtle">{dateText(i.createdAt)}</span></div></div><Status value={i.status}/></div><p className="mt-2 line-clamp-2 text-xs leading-6 text-quiet">{i.message}</p></button>):<div className="p-10 text-center text-sm text-subtle">{q||status?'لا توجد استفسارات مطابقة.':'لا توجد استفسارات بعد.'}</div>}</div>{list.data&&<Pager page={list.data.page} pageSize={list.data.pageSize} total={list.data.total} onPage={setPage}/>}</div><div ref={editorRef} className="scroll-mt-24 xl:sticky xl:top-24">{active?<InquiryEditor key={active.id} inquiry={active}/>:<div className="surface hidden min-h-64 flex-col items-center justify-center p-8 text-center text-subtle xl:flex"><MessageSquareText className="mb-3" size={30} strokeWidth={1.5}/><p className="text-sm">اختر استفسارًا لقراءته والرد عليه.</p></div>}</div></div>}
  </PortalLayout>;
}
 function InquiryEditor({inquiry}:{inquiry:OfficeInquiry}) {
  const qc=useQueryClient();const mutation=useAnswerOfficeInquiry();const [answer,setAnswer]=useState(inquiry.answer??'');const [saved,setSaved]=useState(false);
  useEffect(()=>{setAnswer(inquiry.answer??'');setSaved(false)},[inquiry.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:inquiry.id,data:{answer:answer.trim()}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeInquiriesQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-line bg-sage p-5"><div className="flex items-start justify-between gap-3"><h2 className="display text-lg font-semibold leading-8">{inquiry.subject}</h2><Status value={inquiry.status}/></div><div className="mt-1 text-xs text-subtle">{dateText(inquiry.createdAt)}</div></div><div className="space-y-5 p-5"><CustomerCard customer={inquiry.customer}/>{inquiry.linkedServiceRequest&&<div className="rounded-lg border border-sage-2 bg-paper p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-bold text-subtle">الطلب المرتبط <span dir="ltr" className="nums">{inquiry.linkedServiceRequest.reference}</span></div><Status value={inquiry.linkedServiceRequest.status}/></div><div className="mt-2 font-semibold">{inquiry.linkedServiceRequest.service}<span className="font-normal text-subtle">، {categoryNames[inquiry.linkedServiceRequest.category]}</span></div><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm leading-7 text-quiet">{inquiry.linkedServiceRequest.description}</p></div>}<div><div className="mb-2 text-xs font-bold text-subtle">رسالة العميل</div><p className="whitespace-pre-wrap text-sm leading-8">{inquiry.message}</p></div>{inquiry.answer&&<div className="rounded-lg border-r-[3px] border-copper bg-copper-soft px-4 py-3"><div className="mb-1 flex flex-wrap justify-between gap-2 text-xs font-bold text-copper"><span>الرد الحالي</span><span className="font-normal">{dateText(inquiry.answeredAt)}</span></div><p className="whitespace-pre-wrap text-sm leading-7">{inquiry.answer}</p></div>}<form onSubmit={submit} className="space-y-4 border-t border-line pt-5"><label className="form-field">{inquiry.answer?'تعديل الرد':'الرد'}<textarea className="form-control" value={answer} onChange={e=>setAnswer(e.target.value)} minLength={2} maxLength={5000} placeholder="اكتب الرد" required/><small className="muted font-normal">يظهر الرد للعميل في سجل استفساراته.</small></label>{mutation.isError&&<p role="alert" className="text-xs text-danger">تعذّر إرسال الرد. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-ok">تم حفظ الرد.</p>}<button disabled={mutation.isPending} type="submit" className="btn btn-primary w-full">{mutation.isPending?'جارٍ الإرسال…':inquiry.answer?'حفظ الرد':'إرسال الرد'}<Send size={16}/></button></form></div></div>;
}