import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ClipboardList, MessageSquareText, Save, Search } from 'lucide-react';
import { getGetOfficeSummaryQueryKey, getListOfficeServiceRequestsQueryKey, getListOfficeInquiriesQueryKey, useGetOfficeSummary, useListOfficeServiceRequests, useUpdateOfficeServiceRequest, useListOfficeInquiries, useAnswerOfficeInquiry, type OfficeServiceRequest, type OfficeInquiry, type ServiceRequestUpdateStatus } from '@workspace/api-client-react';
import { PortalLayout, PageHeading, LoadingBlock, ErrorBlock, EmptyBlock, Status, dateText, categoryNames, statusOptions, statusNames } from '@/components/portal-ui';

export function OfficeOverview() {
  const q=useGetOfficeSummary({query:{queryKey:getGetOfficeSummaryQueryKey(),refetchInterval:30000}});
  return <PortalLayout staff><PageHeading eyebrow="مساحة المكتب" title="صندوق المتابعة" subtitle="لقطة سريعة للطلبات والاستفسارات الواردة إلى المكتب."/>
    {q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:q.data&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['إجمالي الطلبات',q.data.totalRequests],['طلبات جديدة',q.data.newRequests],['طلبات نشطة',q.data.activeRequests],['استفسارات مفتوحة',q.data.openInquiries]].map(([label,value],i)=><div className={`surface p-6 ${i===1?'!bg-[#174b50] !text-[#f8f2e8]':''}`} key={label}><div className={`text-xs font-bold ${i===1?'text-[#c6d9d1]':'text-[#74877e]'}`}>{label}</div><div className="display mt-5 text-4xl font-semibold" dir="ltr">{value}</div></div>)}</div><div className="mt-10 grid gap-4 md:grid-cols-2"><Link href="/office/requests" className="group surface flex items-start justify-between gap-4 p-7 text-inherit no-underline transition-transform hover:-translate-y-1"><div><ClipboardList className="mb-7 text-[#b96943]" size={26}/><h2 className="display text-xl font-semibold">طلبات العملاء</h2><p className="muted mt-2 text-sm leading-7">راجع المعاملات وحدّث حالتها وأضف ملاحظات المكتب الداخلية.</p></div><ArrowLeft className="shrink-0 text-[#8b9c93] group-hover:-translate-x-1 transition-transform"/></Link><Link href="/office/inquiries" className="group surface flex items-start justify-between gap-4 p-7 text-inherit no-underline transition-transform hover:-translate-y-1"><div><MessageSquareText className="mb-7 text-[#b96943]" size={26}/><h2 className="display text-xl font-semibold">استفسارات العملاء</h2><p className="muted mt-2 text-sm leading-7">اطّلع على الأسئلة الواردة وأرسل الردود للعملاء.</p></div><ArrowLeft className="shrink-0 text-[#8b9c93] group-hover:-translate-x-1 transition-transform"/></Link></div></>}
  </PortalLayout>;
}
export function OfficeRequests() {
  const q=useListOfficeServiceRequests({query:{queryKey:getListOfficeServiceRequestsQueryKey(),refetchInterval:30000}}); const [selected,setSelected]=useState<number|null>(null); const [search,setSearch]=useState(''); const [filter,setFilter]=useState('all');
  const rows=q.data?.filter(r=>(filter==='all'||r.status===filter)&&(`${r.reference} ${r.service} ${r.description}`.toLowerCase().includes(search.toLowerCase())))??[];
  const active=q.data?.find(r=>r.id===selected);
  return <PortalLayout staff><PageHeading eyebrow="صندوق الوارد" title="طلبات العملاء" subtitle="راجع التفاصيل وحدّث الحالة بحسب تقدم كل طلب."/>
    {q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<EmptyBlock title="لا توجد طلبات واردة" text="ستظهر طلبات العملاء هنا عند إرسالها عبر البوابة."/>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-[#7a9087]" size={17}/><input className="form-control !pr-10" placeholder="ابحث بالرقم أو الخدمة..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="form-control sm:!w-44" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option>{statusOptions.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select></div><div className="surface overflow-hidden">{rows.length?rows.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`block w-full border-b border-[#e9e7dc] p-5 text-right transition-colors last:border-0 hover:bg-[#f5f4ec] ${selected===r.id?'bg-[#e9f0e9]':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-bold">{r.service}</div><div className="mt-2 text-xs text-[#74857d]"><span dir="ltr">{r.reference}</span> · {categoryNames[r.category]} · {dateText(r.createdAt)}</div></div><Status value={r.status}/></div></button>):<div className="p-10 text-center text-sm text-[#77887e]">لا توجد نتائج مطابقة.</div>}</div></div><div className="xl:sticky xl:top-24 xl:self-start">{active?<RequestEditor key={active.id} request={active}/>:<div className="surface flex min-h-64 flex-col items-center justify-center p-8 text-center text-[#70847c]"><ClipboardList className="mb-4" size={32} strokeWidth={1.5}/><p className="text-sm">اختر طلبًا من القائمة لعرض تفاصيله وتحديث حالته.</p></div>}</div></div>}
  </PortalLayout>;
}
function RequestEditor({request}:{request:OfficeServiceRequest}) {
  const qc=useQueryClient(); const mutation=useUpdateOfficeServiceRequest(); const [status,setStatus]=useState<ServiceRequestUpdateStatus>(request.status); const [officeNote,setOfficeNote]=useState(request.officeNote??''); const [saved,setSaved]=useState(false);
  useEffect(()=>{setStatus(request.status);setOfficeNote(request.officeNote??'');setSaved(false)},[request.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:request.id,data:{status,officeNote:officeNote.trim()||null}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeServiceRequestsQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-[#e7e7de] bg-[#eaf0e9] p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-[#739087]" dir="ltr">{request.reference}</span><h2 className="display mt-2 text-lg font-semibold">{request.service}</h2></div><Status value={request.status}/></div></div><div className="space-y-5 p-5"><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="muted block">المجال</span><strong>{categoryNames[request.category]}</strong></div><div><span className="muted block">تاريخ الإرسال</span><strong>{dateText(request.createdAt)}</strong></div><div className="col-span-2"><span className="muted block">رقم التواصل</span><strong dir="ltr" className="inline-block">{request.contactPhone}</strong></div></div><div className="border-t border-[#e8e6dd] pt-4"><div className="mb-2 text-xs font-bold text-[#788b81]">تفاصيل العميل</div><p className="max-h-44 overflow-y-auto whitespace-pre-wrap text-sm leading-7">{request.description}</p></div><form onSubmit={submit} className="space-y-4 border-t border-[#e8e6dd] pt-5"><label className="form-field">تحديث الحالة<select className="form-control" value={status} onChange={e=>setStatus(e.target.value as ServiceRequestUpdateStatus)}>{statusOptions.map(s=><option value={s} key={s}>{statusNames[s]}</option>)}</select></label><label className="form-field">ملاحظة المكتب الداخلية<textarea className="form-control !min-h-28" value={officeNote} onChange={e=>setOfficeNote(e.target.value)} maxLength={2000} placeholder="ملاحظة داخلية للفريق..."/><small className="muted font-normal">هذه الملاحظة داخلية ولا تُعرض للعميل في البوابة.</small></label>{mutation.isError&&<p role="alert" className="text-xs text-[#ad4332]">تعذّر حفظ التحديث. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-[#387551]">تم حفظ التحديث.</p>}<button type="submit" disabled={mutation.isPending} className="btn btn-primary w-full">{mutation.isPending?'جارٍ الحفظ...':'حفظ التحديث'}<Save size={16}/></button></form></div></div>;
}
export function OfficeInquiries(){
  const q=useListOfficeInquiries({query:{queryKey:getListOfficeInquiriesQueryKey(),refetchInterval:30000}});const [selected,setSelected]=useState<number|null>(null);const [filter,setFilter]=useState('open');const rows=q.data?.filter(i=>filter==='all'||i.status===filter)??[];const active=q.data?.find(i=>i.id===selected);
  return <PortalLayout staff><PageHeading eyebrow="صندوق الوارد" title="استفسارات العملاء" subtitle="اقرأ الأسئلة وأجب عنها من مساحة واحدة."/>
    {q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<EmptyBlock title="لا توجد استفسارات" text="ستظهر هنا استفسارات العملاء عند إرسالها عبر البوابة."/>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div><div className="mb-4 flex gap-2">{[['open','المفتوحة'],['answered','المجاب عنها'],['all','الكل']].map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`rounded-full border px-4 py-2 text-xs font-bold ${filter===key?'border-[#174b50] bg-[#174b50] text-[#faf4e9]':'border-[#dce0d5] bg-[#fcfaf4]'}`}>{label}</button>)}</div><div className="surface overflow-hidden">{rows.length?rows.map(i=><button key={i.id} onClick={()=>setSelected(i.id)} className={`block w-full border-b border-[#e8e6dd] p-5 text-right last:border-0 hover:bg-[#f5f4ec] ${selected===i.id?'bg-[#e9f0e9]':''}`}><div className="flex justify-between gap-3"><div><div className="font-bold">{i.subject}</div><div className="muted mt-2 text-xs">{dateText(i.createdAt)}</div></div><Status value={i.status}/></div><p className="muted mt-3 line-clamp-2 text-xs leading-6">{i.message}</p></button>):<div className="p-10 text-center text-sm text-[#77887e]">لا توجد استفسارات في هذا القسم.</div>}</div></div><div className="xl:sticky xl:top-24 xl:self-start">{active?<InquiryEditor key={active.id} inquiry={active}/>:<div className="surface flex min-h-64 flex-col items-center justify-center p-8 text-center text-[#70847c]"><MessageSquareText className="mb-4" size={32} strokeWidth={1.5}/><p className="text-sm">اختر استفسارًا للاطلاع عليه والرد.</p></div>}</div></div>}
  </PortalLayout>;
}
 function InquiryEditor({inquiry}:{inquiry:OfficeInquiry}) {
  const qc=useQueryClient();const mutation=useAnswerOfficeInquiry();const [answer,setAnswer]=useState(inquiry.answer??'');const [saved,setSaved]=useState(false);
  useEffect(()=>{setAnswer(inquiry.answer??'');setSaved(false)},[inquiry.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:inquiry.id,data:{answer:answer.trim()}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeInquiriesQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-[#e6e6dc] bg-[#eaf0e9] p-5"><div className="flex items-center justify-between gap-2"><h2 className="display text-lg font-semibold">{inquiry.subject}</h2><Status value={inquiry.status}/></div><div className="muted mt-2 text-xs">{dateText(inquiry.createdAt)}</div></div><div className="space-y-5 p-5">{inquiry.linkedServiceRequest&&<div className="rounded-lg border border-[#dce4d9] bg-[#f5f7f0] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-bold text-[#6f877c]">طلب الخدمة المرتبط · <span dir="ltr">{inquiry.linkedServiceRequest.reference}</span></div><Status value={inquiry.linkedServiceRequest.status}/></div><div className="mt-2 font-semibold">{inquiry.linkedServiceRequest.service} · {categoryNames[inquiry.linkedServiceRequest.category]}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[#566b67]">{inquiry.linkedServiceRequest.description}</p></div>}<div><div className="mb-2 text-xs font-bold text-[#778b80]">رسالة العميل</div><p className="whitespace-pre-wrap text-sm leading-8">{inquiry.message}</p></div>{inquiry.answer&&<div className="border-r-[3px] border-[#c4714c] bg-[#f7f1e8] p-4"><div className="mb-2 text-xs font-bold text-[#ac613d]">الرد الحالي · {dateText(inquiry.answeredAt)}</div><p className="whitespace-pre-wrap text-sm leading-7">{inquiry.answer}</p></div>}<form onSubmit={submit} className="space-y-4 border-t border-[#e8e6dd] pt-5"><label className="form-field">{inquiry.answer?'تعديل الرد':'اكتب ردّك'}<textarea className="form-control" value={answer} onChange={e=>setAnswer(e.target.value)} minLength={2} maxLength={5000} placeholder="اكتب الرد الذي سيظهر للعميل..." required/></label>{mutation.isError&&<p role="alert" className="text-xs text-[#ad4332]">تعذّر إرسال الرد. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-[#387551]">تم حفظ الرد.</p>}<button disabled={mutation.isPending} type="submit" className="btn btn-primary w-full">{mutation.isPending?'جارٍ الإرسال...':inquiry.answer?'حفظ الرد':'إرسال الرد'}<ArrowLeft size={16}/></button></form></div></div>;
}