import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearch } from 'wouter';
import { keepPreviousData, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ClipboardList, Mail, MessageSquareText, Save, Search, UserRound } from 'lucide-react';
import { getGetOfficeSummaryQueryKey, getListOfficeServiceRequestsQueryKey, getListOfficeInquiriesQueryKey, useGetOfficeSummary, useListOfficeServiceRequests, useUpdateOfficeServiceRequest, useListOfficeInquiries, useAnswerOfficeInquiry, type ListOfficeInquiriesStatus, type ListOfficeServiceRequestsCategory, type ListOfficeServiceRequestsSort, type ListOfficeServiceRequestsStatus, type OfficeCustomer, type OfficeServiceRequest, type OfficeInquiry, type ServiceRequestUpdateStatus } from '@workspace/api-client-react';
import { PortalLayout, PageHeading, LoadingBlock, ErrorBlock, EmptyBlock, Pager, StaleBadge, Status, dateText, categoryNames, isStale, statusOptions, statusNames, useDebouncedValue } from '@/components/portal-ui';

export function OfficeOverview() {
  const q=useGetOfficeSummary({query:{queryKey:getGetOfficeSummaryQueryKey(),refetchInterval:30000}});
  return <PortalLayout staff><PageHeading eyebrow="مساحة المكتب" title="صندوق المتابعة" subtitle="لقطة سريعة للطلبات والاستفسارات الواردة إلى المكتب."/>
    {q.isLoading?<LoadingBlock/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:q.data&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['إجمالي الطلبات',q.data.totalRequests],['طلبات جديدة',q.data.newRequests],['طلبات نشطة',q.data.activeRequests],['استفسارات مفتوحة',q.data.openInquiries]].map(([label,value],i)=><div className={`surface p-6 ${i===1?'!bg-[#174b50] !text-[#f8f2e8]':''}`} key={label}><div className={`text-xs font-bold ${i===1?'text-[#c6d9d1]':'text-[#74877e]'}`}>{label}</div><div className="display mt-5 text-4xl font-semibold" dir="ltr">{value}</div></div>)}</div>{q.data.staleRequests>0&&<Link href="/office/requests?sort=oldest_update" className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#ecd9a4] bg-[#fbf3dc] px-5 py-4 text-sm text-[#6d5413] no-underline transition-colors hover:bg-[#f8ecca]"><span><strong>{new Intl.NumberFormat('ar').format(q.data.staleRequests)}</strong> من الطلبات النشطة لم تُحدَّث منذ 3 أيام أو أكثر.</span><span className="flex items-center gap-1 font-bold">اعرضها من الأقدم<ArrowLeft size={15}/></span></Link>}<div className="mt-10 grid gap-4 md:grid-cols-2"><Link href="/office/requests" className="group surface flex items-start justify-between gap-4 p-7 text-inherit no-underline transition-transform hover:-translate-y-1"><div><ClipboardList className="mb-7 text-[#b96943]" size={26}/><h2 className="display text-xl font-semibold">طلبات العملاء</h2><p className="muted mt-2 text-sm leading-7">راجع المعاملات وحدّث حالتها وأضف ملاحظات المكتب الداخلية.</p></div><ArrowLeft className="shrink-0 text-[#8b9c93] group-hover:-translate-x-1 transition-transform"/></Link><Link href="/office/inquiries" className="group surface flex items-start justify-between gap-4 p-7 text-inherit no-underline transition-transform hover:-translate-y-1"><div><MessageSquareText className="mb-7 text-[#b96943]" size={26}/><h2 className="display text-xl font-semibold">استفسارات العملاء</h2><p className="muted mt-2 text-sm leading-7">اطّلع على الأسئلة الواردة وأرسل الردود للعملاء.</p></div><ArrowLeft className="shrink-0 text-[#8b9c93] group-hover:-translate-x-1 transition-transform"/></Link></div></>}
  </PortalLayout>;
}
// Below the xl breakpoint the editor sits under the list, so bring it into view.
function useRevealOnSelect(selected: number | null) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (selected != null && !window.matchMedia('(min-width: 1280px)').matches) ref.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [selected]);
  return ref;
}
function CustomerLine({customer}:{customer:OfficeCustomer|null}) {
  return customer ? <span className="font-semibold text-[#3f5f5b]">{customer.fullName}</span> : <span className="text-[#8a9892]">عميل بلا طلب تسجيل</span>;
}
function CustomerCard({customer}:{customer:OfficeCustomer|null}) {
  if (!customer) return <div className="rounded-lg bg-[#f3f1e9] p-3 text-xs text-[#6f817a]">لا يوجد طلب تسجيل لهذا العميل في البوابة.</div>;
  return <div className="flex items-start gap-3 rounded-lg bg-[#f3f1e9] p-3"><UserRound className="mt-0.5 shrink-0 text-[#6f877c]" size={18}/><div className="min-w-0 text-xs"><div className="font-bold text-[#173e42]">{customer.fullName}</div><a href={`mailto:${customer.email}`} dir="ltr" className="mt-1 inline-flex items-center gap-1 break-all text-[#1d6164]"><Mail size={13}/>{customer.email}</a></div></div>;
}
const requestSorts: Record<ListOfficeServiceRequestsSort,string> = { newest: 'الأحدث إرسالًا', oldest_update: 'الأقدم تحديثًا' };
export function OfficeRequests() {
  const initial=new URLSearchParams(useSearch());
  const [search,setSearch]=useState(''); const q=useDebouncedValue(search.trim());
  const [status,setStatus]=useState<ListOfficeServiceRequestsStatus|''>(() => (statusOptions as string[]).includes(initial.get('status')??'') ? initial.get('status') as ListOfficeServiceRequestsStatus : '');
  const [category,setCategory]=useState<ListOfficeServiceRequestsCategory|''>('');
  const [sort,setSort]=useState<ListOfficeServiceRequestsSort>(initial.get('sort')==='oldest_update'?'oldest_update':'newest');
  const [page,setPage]=useState(1); const [selected,setSelected]=useState<number|null>(null);
  useEffect(()=>setPage(1),[q,status,category,sort]);
  const params={...(status?{status}:{}),...(category?{category}:{}),...(q?{q}:{}),sort,page};
  const list=useListOfficeServiceRequests(params,{query:{queryKey:getListOfficeServiceRequestsQueryKey(params),placeholderData:keepPreviousData,refetchInterval:30000}});
  const rows=list.data?.items??[]; const active=rows.find(r=>r.id===selected);
  const filtered=Boolean(q||status||category);
  const editorRef=useRevealOnSelect(selected);
  return <PortalLayout staff><PageHeading eyebrow="صندوق الوارد" title="طلبات العملاء" subtitle="ابحث باسم العميل أو بريده أو الرقم المرجعي، وحدّث الحالة بحسب تقدم كل طلب."/>
    <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-[minmax(0,1fr)_repeat(3,11rem)]">
      <label className="relative col-span-2 lg:col-span-1"><span className="sr-only">بحث</span><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-[#7a9087]" size={17}/><input className="form-control !pr-10" placeholder="اسم العميل، البريد، الرقم المرجعي، الخدمة..." value={search} onChange={e=>setSearch(e.target.value)} maxLength={120}/></label>
      <label><span className="sr-only">الحالة</span><select className="form-control" value={status} onChange={e=>setStatus(e.target.value as ListOfficeServiceRequestsStatus|'')}><option value="">كل الحالات</option>{statusOptions.map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select></label>
      <label><span className="sr-only">المجال</span><select className="form-control" value={category} onChange={e=>setCategory(e.target.value as ListOfficeServiceRequestsCategory|'')}><option value="">كل المجالات</option>{Object.entries(categoryNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <label className="col-span-2 lg:col-span-1"><span className="sr-only">الترتيب</span><select className="form-control" value={sort} onChange={e=>setSort(e.target.value as ListOfficeServiceRequestsSort)}>{Object.entries(requestSorts).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
    </div>
    {list.isLoading?<LoadingBlock/>:list.isError?<ErrorBlock retry={()=>list.refetch()}/>:!list.data?.total&&!filtered?<EmptyBlock title="لا توجد طلبات واردة" text="ستظهر طلبات العملاء هنا عند إرسالها عبر البوابة."/>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div><div className={`surface overflow-hidden transition-opacity ${list.isPlaceholderData?'opacity-60':''}`}>{rows.length?rows.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`block w-full border-b border-[#e9e7dc] p-5 text-right transition-colors last:border-0 hover:bg-[#f5f4ec] ${selected===r.id?'bg-[#e9f0e9]':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-bold">{r.service}</div><div className="mt-1 text-xs"><CustomerLine customer={r.customer}/></div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-[#74857d]"><span dir="ltr">{r.reference}</span><span>{categoryNames[r.category]}</span><span>{dateText(r.createdAt)}</span>{isStale(r)&&<StaleBadge updatedAt={r.updatedAt}/>}</div></div><Status value={r.status}/></div></button>):<div className="p-10 text-center text-sm text-[#77887e]">لا توجد نتائج مطابقة.</div>}</div>{list.data&&<Pager page={list.data.page} pageSize={list.data.pageSize} total={list.data.total} onPage={setPage}/>}</div><div ref={editorRef} className="scroll-mt-24 xl:sticky xl:top-24 xl:self-start">{active?<RequestEditor key={active.id} request={active}/>:<div className="surface flex min-h-64 flex-col items-center justify-center p-8 text-center text-[#70847c]"><ClipboardList className="mb-4" size={32} strokeWidth={1.5}/><p className="text-sm">اختر طلبًا من القائمة لعرض تفاصيله وتحديث حالته.</p></div>}</div></div>}
  </PortalLayout>;
}
function RequestEditor({request}:{request:OfficeServiceRequest}) {
  const qc=useQueryClient(); const mutation=useUpdateOfficeServiceRequest(); const [status,setStatus]=useState<ServiceRequestUpdateStatus>(request.status); const [officeNote,setOfficeNote]=useState(request.officeNote??''); const [saved,setSaved]=useState(false);
  useEffect(()=>{setStatus(request.status);setOfficeNote(request.officeNote??'');setSaved(false)},[request.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:request.id,data:{status,officeNote:officeNote.trim()||null}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeServiceRequestsQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-[#e7e7de] bg-[#eaf0e9] p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-[#739087]" dir="ltr">{request.reference}</span><h2 className="display mt-2 text-lg font-semibold">{request.service}</h2></div><Status value={request.status}/></div></div><div className="space-y-5 p-5"><CustomerCard customer={request.customer}/>{isStale(request)&&<StaleBadge updatedAt={request.updatedAt}/>}<div className="grid grid-cols-2 gap-3 text-xs"><div><span className="muted block">المجال</span><strong>{categoryNames[request.category]}</strong></div><div><span className="muted block">تاريخ الإرسال</span><strong>{dateText(request.createdAt)}</strong></div><div className="col-span-2"><span className="muted block">رقم التواصل</span><strong dir="ltr" className="inline-block">{request.contactPhone}</strong></div></div><div className="border-t border-[#e8e6dd] pt-4"><div className="mb-2 text-xs font-bold text-[#788b81]">تفاصيل العميل</div><p className="max-h-44 overflow-y-auto whitespace-pre-wrap text-sm leading-7">{request.description}</p></div><form onSubmit={submit} className="space-y-4 border-t border-[#e8e6dd] pt-5"><label className="form-field">تحديث الحالة<select className="form-control" value={status} onChange={e=>setStatus(e.target.value as ServiceRequestUpdateStatus)}>{statusOptions.map(s=><option value={s} key={s}>{statusNames[s]}</option>)}</select></label><label className="form-field">ملاحظة المكتب الداخلية<textarea className="form-control !min-h-28" value={officeNote} onChange={e=>setOfficeNote(e.target.value)} maxLength={2000} placeholder="ملاحظة داخلية للفريق..."/><small className="muted font-normal">هذه الملاحظة داخلية ولا تُعرض للعميل في البوابة.</small></label>{mutation.isError&&<p role="alert" className="text-xs text-[#ad4332]">تعذّر حفظ التحديث. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-[#387551]">تم حفظ التحديث.</p>}<button type="submit" disabled={mutation.isPending} className="btn btn-primary w-full">{mutation.isPending?'جارٍ الحفظ...':'حفظ التحديث'}<Save size={16}/></button></form></div></div>;
}
const inquiryFilters: [ListOfficeInquiriesStatus|'', string][] = [['open','المفتوحة'],['answered','المجاب عنها'],['','الكل']];
export function OfficeInquiries(){
  const [search,setSearch]=useState(''); const q=useDebouncedValue(search.trim());
  const [status,setStatus]=useState<ListOfficeInquiriesStatus|''>('open'); const [page,setPage]=useState(1); const [selected,setSelected]=useState<number|null>(null);
  useEffect(()=>setPage(1),[q,status]);
  const params={...(status?{status}:{}),...(q?{q}:{}),page};
  const list=useListOfficeInquiries(params,{query:{queryKey:getListOfficeInquiriesQueryKey(params),placeholderData:keepPreviousData,refetchInterval:30000}});
  const rows=list.data?.items??[]; const active=rows.find(i=>i.id===selected);
  const editorRef=useRevealOnSelect(selected);
  return <PortalLayout staff><PageHeading eyebrow="صندوق الوارد" title="استفسارات العملاء" subtitle="اقرأ الأسئلة وأجب عنها من مساحة واحدة."/>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="flex gap-2">{inquiryFilters.map(([key,label])=><button key={label} onClick={()=>setStatus(key)} aria-pressed={status===key} className={`rounded-full border px-4 py-2 text-xs font-bold ${status===key?'border-[#174b50] bg-[#174b50] text-[#faf4e9]':'border-[#dce0d5] bg-[#fcfaf4]'}`}>{label}</button>)}</div><label className="relative flex-1"><span className="sr-only">بحث</span><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-[#7a9087]" size={17}/><input className="form-control !pr-10" placeholder="اسم العميل، البريد، الموضوع..." value={search} onChange={e=>setSearch(e.target.value)} maxLength={120}/></label></div>
    {list.isLoading?<LoadingBlock/>:list.isError?<ErrorBlock retry={()=>list.refetch()}/>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div><div className={`surface overflow-hidden transition-opacity ${list.isPlaceholderData?'opacity-60':''}`}>{rows.length?rows.map(i=><button key={i.id} onClick={()=>setSelected(i.id)} className={`block w-full border-b border-[#e8e6dd] p-5 text-right last:border-0 hover:bg-[#f5f4ec] ${selected===i.id?'bg-[#e9f0e9]':''}`}><div className="flex justify-between gap-3"><div className="min-w-0"><div className="font-bold">{i.subject}</div><div className="mt-1 text-xs"><CustomerLine customer={i.customer}/></div><div className="muted mt-1 text-xs">{dateText(i.createdAt)}</div></div><Status value={i.status}/></div><p className="muted mt-3 line-clamp-2 text-xs leading-6">{i.message}</p></button>):<div className="p-10 text-center text-sm text-[#77887e]">{q||status?'لا توجد استفسارات مطابقة.':'ستظهر هنا استفسارات العملاء عند إرسالها عبر البوابة.'}</div>}</div>{list.data&&<Pager page={list.data.page} pageSize={list.data.pageSize} total={list.data.total} onPage={setPage}/>}</div><div ref={editorRef} className="scroll-mt-24 xl:sticky xl:top-24 xl:self-start">{active?<InquiryEditor key={active.id} inquiry={active}/>:<div className="surface flex min-h-64 flex-col items-center justify-center p-8 text-center text-[#70847c]"><MessageSquareText className="mb-4" size={32} strokeWidth={1.5}/><p className="text-sm">اختر استفسارًا للاطلاع عليه والرد.</p></div>}</div></div>}
  </PortalLayout>;
}
 function InquiryEditor({inquiry}:{inquiry:OfficeInquiry}) {
  const qc=useQueryClient();const mutation=useAnswerOfficeInquiry();const [answer,setAnswer]=useState(inquiry.answer??'');const [saved,setSaved]=useState(false);
  useEffect(()=>{setAnswer(inquiry.answer??'');setSaved(false)},[inquiry.id]);
  async function submit(e:FormEvent){e.preventDefault();setSaved(false);try{await mutation.mutateAsync({id:inquiry.id,data:{answer:answer.trim()}});await Promise.all([qc.invalidateQueries({queryKey:getListOfficeInquiriesQueryKey()}),qc.invalidateQueries({queryKey:getGetOfficeSummaryQueryKey()})]);setSaved(true)}catch{/* error shown */}}
  return <div className="surface overflow-hidden"><div className="border-b border-[#e6e6dc] bg-[#eaf0e9] p-5"><div className="flex items-center justify-between gap-2"><h2 className="display text-lg font-semibold">{inquiry.subject}</h2><Status value={inquiry.status}/></div><div className="muted mt-2 text-xs">{dateText(inquiry.createdAt)}</div></div><div className="space-y-5 p-5"><CustomerCard customer={inquiry.customer}/>{inquiry.linkedServiceRequest&&<div className="rounded-lg border border-[#dce4d9] bg-[#f5f7f0] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-bold text-[#6f877c]">طلب الخدمة المرتبط: <span dir="ltr">{inquiry.linkedServiceRequest.reference}</span></div><Status value={inquiry.linkedServiceRequest.status}/></div><div className="mt-2 font-semibold">{inquiry.linkedServiceRequest.service}<span className="font-normal text-[#6f877c]">، {categoryNames[inquiry.linkedServiceRequest.category]}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[#566b67]">{inquiry.linkedServiceRequest.description}</p></div>}<div><div className="mb-2 text-xs font-bold text-[#778b80]">رسالة العميل</div><p className="whitespace-pre-wrap text-sm leading-8">{inquiry.message}</p></div>{inquiry.answer&&<div className="border-r-[3px] border-[#c4714c] bg-[#f7f1e8] p-4"><div className="mb-2 text-xs font-bold text-[#ac613d]">الرد الحالي، {dateText(inquiry.answeredAt)}</div><p className="whitespace-pre-wrap text-sm leading-7">{inquiry.answer}</p></div>}<form onSubmit={submit} className="space-y-4 border-t border-[#e8e6dd] pt-5"><label className="form-field">{inquiry.answer?'تعديل الرد':'اكتب ردّك'}<textarea className="form-control" value={answer} onChange={e=>setAnswer(e.target.value)} minLength={2} maxLength={5000} placeholder="اكتب الرد الذي سيظهر للعميل..." required/></label>{mutation.isError&&<p role="alert" className="text-xs text-[#ad4332]">تعذّر إرسال الرد. حاول مجددًا.</p>}{saved&&<p role="status" className="text-xs font-bold text-[#387551]">تم حفظ الرد.</p>}<button disabled={mutation.isPending} type="submit" className="btn btn-primary w-full">{mutation.isPending?'جارٍ الإرسال...':inquiry.answer?'حفظ الرد':'إرسال الرد'}<ArrowLeft size={16}/></button></form></div></div>;
}